### PR TITLE
GUI Version of Hangman

### PR DESCRIPTION
**Pull request by ambushneupane**
Created a GUI version of Hangman game .

### CODE REVIEW

**Comment by ambushneupane** [comment]
Hey @anantdark What is that cross? How do i get this merged?

**Comment by anantdark** [comment]
@ambushneupane that is from the automated checks, i am reviewing your PR, will merge soon.

**Comment by ambushneupane** [comment]
Let me know If anything goes wrong.

**Review by anantdark — CHANGES_REQUESTED** [review]
Looking good, would like to suggest some changes before merging.

Currently your program is using words from a small list.

Change the code to use random words from a separate module. You can also just import the wordgen module from hangman-cli, or add your own.

**Comment by ambushneupane** [comment]
Increased the words and created separate module to deal with the words. I did play around with random word module but the words were very unlikely to be guessed so Didn't include it. I think It's ready to get merged.

**Pull request merged**
